# Generated by Django 4.0.10 on 2024-03-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindBus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='s_type',
            field=models.CharField(choices=[('predefinned', 'Pre-definned'), ('custom', 'Custom')], default='Custom', max_length=30),
            preserve_default=False,
        ),
    ]
