# Generated by Django 4.0.10 on 2024-03-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindBus', '0002_suggestion_s_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='details',
        ),
    ]
