# Generated by Django 4.0.10 on 2024-03-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindBus', '0003_remove_suggestion_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
