# Generated by Django 4.0.10 on 2024-01-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stands', '0002_alter_area_options_alter_stand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['a_name']},
        ),
        migrations.AlterModelOptions(
            name='stand',
            options={'ordering': ['s_name']},
        ),
    ]
