# Generated by Django 4.0.10 on 2024-02-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stands', '0003_alter_area_options_alter_stand_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='a_name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='stand',
            name='area',
        ),
        migrations.AddField(
            model_name='stand',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, to='Stands.area'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='s_name',
            field=models.CharField(max_length=100),
        ),
    ]
