# Generated by Django 4.0.10 on 2024-02-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stands', '0004_alter_area_a_name_remove_stand_area_stand_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='a_no',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stand',
            name='s_no',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stand',
            name='area',
            field=models.ManyToManyField(to='Stands.area'),
        ),
    ]
