# Generated by Django 4.0.10 on 2024-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('view', 'View'), ('suggest', 'Suggest'), ('search', 'Search'), ('try', 'Try'), ('submit', 'Submit')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='LogCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField(default=0)),
            ],
        ),
    ]
