# Generated by Django 4.0.10 on 2024-01-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='name',
            new_name='b_name',
        ),
    ]
