# Generated by Django 4.0.10 on 2024-01-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0002_rename_name_bus_b_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderingmodel',
            options={},
        ),
    ]
