# Generated by Django 4.0.10 on 2024-01-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0004_alter_orderingmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderingmodel',
            options={'ordering': ['-bus']},
        ),
    ]
