# Generated by Django 4.0.10 on 2024-01-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0005_alter_orderingmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderingmodel',
            options={'ordering': ['-bus', 'order']},
        ),
    ]
