# Generated by Django 4.0.10 on 2024-02-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0008_alter_bus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingmodel',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
