# Generated by Django 4.0.10 on 2024-02-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0010_alter_bus_options_bus_isactive_bus_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='b_no',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
