AreaData={
    "1":{"name":"Agargoan"},
    "55":{"name":"Ashulia"},
    "2":{"name":"Azimpur"},
    "3":{"name":"Badda"},
    "4":{"name":"Banani"},
    "51":{"name":"Banasree"},
    "5":{"name":"Bashundhara"},
    "6":{"name":"Cantonment"},
    "7":{"name":"Demra"},
    "8":{"name":"Dhanmondi"},
    "9":{"name":"Donia"},
    "10":{"name":"ECB"},
    "54":{"name":"Elephant Road"},
    "11":{"name":"Farmgate"},
    "12":{"name":"Gabtoli"},
    "13":{"name":"Gazipur"},
    "14":{"name":"Gendaria"},
    "15":{"name":"Gulistan"},
    "16":{"name":"Gulshan"},
    "17":{"name":"Jatrabari"},
    "18":{"name":"Kakrail"},
    "19":{"name":"Kamalapur"},
    "20":{"name":"Kanchpur"},
    "21":{"name":"Keraniganj"},
    "22":{"name":"Khilgoan"},
    "23":{"name":"Kolabagan"},
    "24":{"name":"Kuril"},
    "25":{"name":"Lalbagh"},
    "26":{"name":"Malibagh"},
    "27":{"name":"Manikganj"},
    "59":{"name":"Mawa"},
    "28":{"name":"Mirpur"},
    "29":{"name":"Mohakhali"},
    "30":{"name":"Mohammadpur"},
    "52":{"name":"Mogbazar"},
    "31":{"name":"Motijheel"},
    "32":{"name":"Munshiganj"},
    "33":{"name":"Naraynganj"},
    "34":{"name":"Nilkhet"},
    "53":{"name":"Notun Bazar"},
    "35":{"name":"Puran Dhaka"},
    "47":{"name":"Purbachol"},
    "36":{"name":"Rampura"},
    "58":{"name":"Ramna"},
    "37":{"name":"Rayer Bazar"},
    "38":{"name":"Sadarghat"},
    "39":{"name":"Savar"},
    "40":{"name":"Shahbag"},
    "41":{"name":"Shantinagar"},
    "42":{"name":"Shewrapara"},
    "43":{"name":"Shyamoli"},
    "56":{"name":"Sayedabad"},
    "57":{"name":"Sign Board"},
    "44":{"name":"Tejgoan"},
    "45":{"name":"Tongi"},
    "46":{"name":"Uttara"},
    
    #New
    
    "48":{"name":"DU"},
    "49":{"name":"BUET"},
    "50":{"name":"DMC"},
    
    #59 exists
}